import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import dynamic from 'next/dynamic'
const Providers = dynamic(() => import('./providers'), { ssr: false })



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html >
      <body >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}